[package]
name = "shkeleton"
version = "0.1.4"
authors = ["Artem Shein <sc-github@aisys.ru>"]

description = "Skeleton rust project"
repository = "https://github.com/artemshein/shkeleton"
categories = ["development-tools"]
license = "MIT"

[dependencies]
log = "0.4"
byteorder = "1"
lazy_static = "1"
array_tool = "1"
itertools = "0.7"
regex = "0.2"
url = "1"
simple_logger = { version = "0.5", optional = true }
fern = { version = "0.5", optional = true }
clap = { version = "2.31", optional = true }
scoped-pool = { version = "1", optional = true }
num_cpus = { version = "1", optional = true }
parking_lot = { version = "0.5", optional = true }

[features]
default = []
cli = ["clap", "simple_logger", "fern"]
concurrency = ["scoped-pool", "num_cpus", "parking_lot"]
