[package]
name = "shkeleton"
version = "0.8.0"
authors = ["Artem Shein <artem.shein@aisys.ru>"]
edition = "2018"

description = "Skeleton rust project"
repository = "https://github.com/artemshein/shkeleton"
categories = ["development-tools"]
license = "MIT"

[dependencies]
sherr = "0.2.9"
byteorder = "1.3.1"
lazy_static = "1.3"
array_tool = "1"
itertools = "0.8"
regex = "1.1.2"
url = "2.1"
derive_more = "0.15"
derive_deref = "1.0.2"
chrono = "0.4.6"
dirs = "2.0.2"
clap = { version = "2.32", optional = true }
scoped-pool = { version = "1", optional = true }
num_cpus = { version = "1.10", optional = true }
parking_lot = { version = "0.9.0", optional = true }
glob = { version = "0.3", optional = true }

[features]
default = []
cli = ["clap", "glob", "sherr/impl"]
concurrency = ["scoped-pool", "num_cpus", "parking_lot"]
failure = ["sherr/fail"]
