[package]
name = "shkeleton"
version = "0.9.1"
authors = ["Artem Shein <artem.shein@aisys.ru>"]
edition = "2018"

description = "Skeleton rust project"
repository = "https://github.com/artemshein/shkeleton"
categories = ["development-tools"]
license = "MIT"

[dependencies]
sherr = "0.3.0"
byteorder = "1.3.1"
lazy_static = "1.3"
array_tool = "1"
itertools = "0.9"
regex = "1.3.1"
url = "2.1"
percent-encoding = "2.1.0"
derive_more = "0.99.2"
derive_deref = "1.0.2"
chrono = "0.4.10"
dirs = "2.0.2"
fstrings = "0.2.2"
fehler = "1.0.0"
clap = { version = "2.32", optional = true }
scoped-pool = { version = "1", optional = true }
num_cpus = { version = "1.10", optional = true }
parking_lot = { version = "0.10.0", optional = true }
glob = { version = "0.3", optional = true }

[features]
default = []
cli = ["clap", "glob", "sherr/impl"]
concurrency = ["scoped-pool", "num_cpus", "parking_lot"]
deadlock_detection = ["parking_lot/deadlock_detection"]
