[package]
name = "shkeleton"
version = "0.4.0"
authors = ["Artem Shein <artem.shein@aisys.ru>"]

description = "Skeleton rust project"
repository = "https://github.com/artemshein/shkeleton"
categories = ["development-tools"]
license = "MIT"

[dependencies]
sherr = "0.1"
byteorder = "1"
lazy_static = "1"
array_tool = "1"
itertools = "0.7"
regex = "1"
url = "1"
derive_more = "0.11"
derive_deref = "1"
chrono = "0.4"
clap = { version = "2", optional = true }
scoped-pool = { version = "1", optional = true }
num_cpus = { version = "1", optional = true }
parking_lot = { version = "0.6", optional = true }
glob = { version = "0.2", optional = true }

[features]
default = []
cli = ["clap", "glob", "sherr/impl"]
concurrency = ["scoped-pool", "num_cpus", "parking_lot"]

[[test]]
name = "test_compile"
required-features = ["cli", "concurrency"]
